services:
  # Web Service for PHP Application
  - type: web
    name: connecthub
    env: php
    buildCommand: |
      # Create required directories with proper permissions
      mkdir -p uploads/profiles uploads/posts
      chmod -R 755 uploads
    startCommand: |
      # Apply database migrations
      php db-init.php
      # Start PHP server with Apache configuration
      heroku-php-apache2
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: BASE_URL
        sync: false
        value: https://connecthub.onrender.com
      - key: DEBUG
        value: false
      - key: UPLOAD_DIR_PROFILES
        value: uploads/profiles
      - key: UPLOAD_DIR_POSTS
        value: uploads/posts
    healthCheckPath: /
    autoDeploy: true
    domains:
      - connecthub.onrender.com
    # Handling static assets
    staticPublishPath: ./

databases:
  # MySQL Database
  - name: connecthub-db
    plan: standard
    databaseName: social_network
    user: connecthub_user
